numbers = [5, 2, 1, 9, 9, 7, 4]
print(numbers)
numbers.append(20)
print(numbers)
numbers.insert(0, 10)
print(numbers)
numbers.remove(4)
print(numbers)
numbers.pop()
print(numbers)
print(numbers.index(5))
print(50 in numbers)
print(numbers.count(9))
print(numbers.sort())
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
numbers.append(10)
print(numbers2)
numbers.clear()
print(numbers)