import turtle
j = turtle.Pen()
j.speed(0)
j.shape("turtle")
j.color("midnight blue")
j.width(2)
bg = turtle.Screen()
bg.bgcolor("lavender blush")
for i in range(0, 36):
    j.down()
    j.circle(70)
    j.left(10)
j.color("gold")
j.up()
j.goto(-400, 300)
j.left(180)
for i in range (0, 36):
    j.down()
    j.circle(70)
    j.left(10)
j.color("red")
j.right(180)
j.up()
j.goto(400, 300)
for i in range (0, 36):
    j.down()
    j.circle(60)
    j.left(10)
j.color("dark violet")
j.right(90)
j.up()
j.goto(400, -300)
for i in range (0, 36):
    j.down()
    j.circle(70)
    j.left(10)
j.color("lawn green")
j.right(90)
j.up()
j.goto(-400, -300)
for i in range (0, 36):
    j.down()
    j.circle(70)
    j.left(10)